### ISSUE TITLE
Better Goat$$ amount reading

### ISSUE THREAD

**Issue by mattverley** [YvesPhilippot/Goat-clicker#3]
Currently the string representing the player's score (or amount of Goat$$) is quite raw with following digits in a difficult to read line.
I propose the American way of delimiting groups of 3 numbers and a dot to mark the decimals:
**1000** -> **1,000**
**1000000,50** -> **1,000,000.50**

If it's too difficult to implement, I recommend at least the spacing of groups of 3 digits.

**Comment by YvesPhilippot** [comment]
Implemented, to test.

**Comment by YvesPhilippot** [comment]
Tested : OK
